pagopa/portale-fatturazione-infra

.pre-commit-config.yaml
src/core/.terraform.lock.hcl
src/core/00_azuread.tf
src/core/00_dns.tf
src/core/00_key_vault.tf
src/core/00_resource_groups.tf
src/core/00_vnet.tf
src/core/10_appgateway.tf
src/core/10_vpn.tf
src/core/20_appservice.tf
src/core/20_sql.tf
src/core/20_storage.tf
src/core/20_synapse.tf
src/core/80_observability.tf
src/core/99_main.tf
src/core/99_variables.tf
src/core/README.md
src/core/env/prod/terraform.tfvars

This PR introduces all resources required by the v0.4 architecture, with the exception of PowerBI.
This is an incomplete PR as it is still lacking private endpoints, pipelines and other configs that are necessary in a production environment.
The production environment is empty, this skeleton can be modified at will.
Terraform skeleton.
---

feature: implement reference v0.4 arch

---

src/core/.terraform.lock.hcl
src/core/00_dns.tf
src/core/00_vnet.tf
src/core/20_appservice.tf
src/core/README.md
src/core/env/prod/terraform.tfvars

feature: create private endpoints for appservice

---

src/azuredevops/.env/backend.ini
src/azuredevops/.env/core_state.tfvars
src/azuredevops/.env/terraform.tfvars
src/azuredevops/core/.terraform.lock.hcl
src/azuredevops/core/00_keyvault.tf
src/azuredevops/core/00_project.tf
src/azuredevops/core/00_secrets_core.tf
src/azuredevops/core/00_service_connections_github.tf
src/azuredevops/core/03_service_connection_tls_certificate_dev.tf
src/azuredevops/core/03_service_connection_tls_certificate_prod.tf
src/azuredevops/core/10_tlscert_dev-portalefatturazione-pagopa-it.tf
src/azuredevops/core/10_tlscert_portalefatturazione-pagopa-it.tf
src/azuredevops/core/99_main.tf
src/azuredevops/core/99_variables.tf
src/azuredevops/core/99_variables_dev.tf
src/azuredevops/core/99_variables_prod.tf
src/azuredevops/core/README.md
src/azuredevops/core/TODO.md
src/azuredevops/terraform.sh

Add provisioning of Azure DevOps pipelines for automatic rotation of Portale Fatturazione TLS certs with ACME.
- Obtain and store Let's Encrypt credentials in Key Vault
- Create federated service endpoints in Azure DevOps project and related User Assigned Managed Identity to Get and Import certificates from KeyVault. 
- Create federated service endpoints in Azure DevOps project and related User Assigned Managed Identity to edit a TXT record in the DNS zone.
- Create Azure DevOps pipeline that uses those service endpoints for pulling the cert, checking if it is to be renewed and renew it with ACME if needed. The ACME challenge consists in writing the TXT record on DNS zone.
Allows automatic certificate rotation.
---

feat: Add azure DevOps pipelines for automatic TLS cert rotation

---

.github/workflows/static_analysis.yml
.identity/env/prod/backend.ini
.identity/env/prod/backend.tfvars
src/azuredevops/core/.terraform.lock.hcl
src/azuredevops/core/99_main.tf.ci
src/core/00_key_vault.tf
src/core/00_vnet.tf
src/core/10_appgateway.tf
src/core/10_vpn.tf
src/core/20_appservice.tf
src/core/20_storage.tf
src/core/99_main.tf
src/core/99_main.tf.ci
src/core/README.md

fix: CICD static analysys

---

src/core/00_dns.tf

feat: remove scm private link

---

src/core/00_dns.tf
src/core/20_sql.tf
src/core/README.md

feat: add sql private endpoint and dns zone

---

src/core/00_dns.tf
src/core/README.md

feat:remove-scm-zone

---

src/core/00_vnet.tf
src/core/20_sql.tf

fix sql privte endpoint

---

src/core/20_sql.tf
src/core/20_synapse.tf
src/core/README.md

chore: change administrator for sql and synapse

---

src/core/00_resource_groups.tf
src/core/README.md

fix: Add identity resource groups

---

src/azuredevops/.env/terraform.tfvars
src/azuredevops/core/03_service_connection_tls_certificate_dev.tf
src/azuredevops/core/03_service_connection_tls_certificate_prod.tf
src/azuredevops/core/10_tlscert_api-portalefatturazione-pagopa-it.tf
src/azuredevops/core/10_tlscert_dev-portalefatturazione-pagopa-it.tf
src/azuredevops/core/10_tlscert_portalefatturazione-pagopa-it.tf
src/azuredevops/core/99_variables_dev.tf
src/azuredevops/core/99_variables_prod.tf
src/azuredevops/core/README.md
src/azuredevops/terraform.sh

feat: Add api.portalefatturazione.pagopa.it certificate

---

src/core/00_dns.tf
src/core/00_resource_groups.tf
src/core/00_vnet.tf
src/core/99_variables.tf
src/core/env/prod/terraform.tfvars

Private endpoints for storage will be fixed with #15.
---
This PR was not yet applied.

[TCE-169][TCE-208] create peered vnet in secondary location

---

src/core/00_dns.tf
src/core/20_storage.tf

[TCE-169][TCE-206] Create dfs pvt dns zone, links and fix references

---

src/core/20_appservice.tf

[TCE-169] [TCE-201] AppService vNET integration

---

src/core/00_dns.tf
src/core/10_appgateway.tf
src/core/20_appservice.tf
src/core/99_variables.tf
src/core/env/prod/terraform.tfvars

This infra code will be removed once we reach the first milestone, moving to #23 
---

[TCE-169][TCE-213] Temporarily use an AppService for serving the frontend

---

src/core/10_vpn.tf
src/core/20_appservice.tf
src/core/20_sql.tf
src/core/80_observability.tf
src/core/env/prod/terraform.tfvars

In addition to CORS (which required abandoning the app_service module) and switching to a zone_redundant P0v3 plan, this  PR includes some opportunistic style fixes.
---

[TCE-169][TCE-202] Enable CORS on "api", use multi-az plan P0v3

---

src/core/00_key_vault.tf

Add additional kv for app service secrets

---

src/core/00_dns.tf
src/core/20_sql.tf
src/core/20_storage.tf
src/core/20_synapse.tf

faet: [TCE219] [TCE220] [TCE221] Add synapse improvements

---

src/core/20_appservice.tf

[TCE-169][TCE-223] Temporarily change publishing mode for all appservices

---

src/core/00_azuread.tf
src/core/00_key_vault.tf
src/core/20_sql.tf
src/core/20_synapse.tf

[TCE-169][TCE-225] Declare synapse roles in Terraform and close public access for workspace

---

src/core/init-db/prod/auth.sql
src/core/init-db/view-auth.sql

The init-db files are meant to be executed manually and not in a pipeline.
---

[TCE-169][TCE-224] Update init-db scripts

---

.pre-commit-config.yaml
src/core/20_synapse.tf

- fix private endpoint synapse
- disable terraform docs
- Synapse studio access only with vpn
---

fix: [TCE-226] Private endpoint synapse

---

src/core/00_key_vault.tf
src/core/20_appservice.tf

fix: Configure App service backend and kv access policy

---

src/core/10_appgateway.tf
src/core/20_appservice.tf
src/core/20_storage.tf
src/core/20_synapse.tf

feat: Update configs

---

src/core/20_storage.tf
src/core/99_variables.tf
src/core/env/prod/terraform.tfvars

[TCE-169][TCE-179] Implement network filtering for sa storage (datalake)

---

src/core/20_appservice.tf
src/core/20_storage.tf
src/core/20_synapse.tf
src/core/init-db/prod/auth.sql

fix: pre prod

---

src/core/20_appservice.tf
src/core/20_storage.tf
src/core/20_synapse.tf

fix: preprod v2

---

src/core/20_appservice.tf

add variables to appservice

---

src/core/20_storage.tf

remove soft blob delete from sap_storage

---

src/core/20_appservice.tf

- [x ] Update configuration to existing resources
---

add-env-variable-to-appservice

---

src/azuredevops/core/10_tlscert_api-portalefatturazione-pagopa-it.tf

fix schedule 10_tlscert_api-portalefatturazione-pagopa-it

---

src/core/20_storage.tf

modified:   src/core/20_storage.tf

---

src/core/30_grafana.tf

- Grafana resoure added
Required by Service Management dashboard content editing
---

Add Grafana dashboard

---

src/core/30_grafana.tf

Change Grafana location to North Europe

---

src/core/20_appservice.tf
src/core/20_functionapp.tf
src/core/30_natgateway.tf

Add an Azure Function, with all ancillary infrastructure, for sending notification emails (PEC).
- Add Azure Function in the same plan as the fatturazione app
- Private endpoint for private connectivity of the function
- VNET integration for outbound traffic
- NAT gateway for outbound traffic
- Configurations of the function from KeyVault
Send notification emails via PEC.
For applying only this modifications (useful in case of drifts in previous infrastructure) use this targeted command (in the `src/core` directory:
```shell
./terraform.sh apply prod \
-target azurerm_storage_account.function \
-target azurerm_linux_function_app.send_email \
-target azurerm_app_service_virtual_network_swift_connection.send_email_function \
-target azurerm_private_endpoint.send_email_function \
-target …
```

feat: Azure Function for sending email

---

src/core/20_functionapp.tf
src/core/init-db/prod/auth.sql

Respect naming convention and add SQL Server authentication.
- Rename storage account of the "send email" function
- Add SQL Server user for the system assigned managed identity of the "send email" function
- Respect naming convention
- Allow function to access database
(Technically, renaming storage account means destroy and recreate it)
---

fix: Naming convention and SQL authentication

---

src/core/20_appservice.tf
src/core/20_functionapp.tf
src/core/20_storage.tf
src/core/30_grafana.tf

fix disallineamenti e aggiunta istanze p0v3

---

src/azuredevops/core/00_secrets_core.tf
src/azuredevops/core/20_sync_github_pipelines.tf

Add syncing pipelines for the following repos:
- [portale-fatturazione-be](https://github.com/pagopa/portale-fatturazione-be)
- [portale-fatturazione-fe](https://github.com/pagopa/portale-fatturazione-fe)
- [portale-fatturazione-synapse](https://github.com/pagopa/portale-fatturazione-synapse)
Keep in sync the Azure DevOps repos with GitHub repos of Portale Fatturazione
---

feat: Add pipelines for syncing Azure DevOps repos with GitHub

---

src/core/env/prod/terraform.tfvars

* Scale app service plan in PROD from `P0v3` to `P1v3`
Too much usage of memory and CPU in PROD environment.
---

feat: Prod service plan sku P0v3 -> P1v3

---

src/core/20_appservice.tf

Add role "Synapse Credential User" to the API app service-assigned managed identity.
The documentation [here](https://learn.microsoft.com/en-us/azure/synapse-analytics/security/synapse-workspace-understand-what-role-you-need#tasks-and-required-roles) says:
> Execute/run a pipeline -> Synapse User and Synapse Credential User on the WorkspaceSystemIdentity
but this is not true, as this setup will lead to:
```http
HTTP/2 401 
content-type: application/json; charset=UTF-8
server: Kestrel Microsoft-HTTPAPI/2.0
strict-transport-security: max-age=31536000; includeSubDomains
x-ms-correlation-request-id: xxx
x-ms-request-id: xxx
date: xxx
{"code":"AccessControlUnauthorized","message":"Insufficient permissions to call this API. <my app managed id object id> does not have …
```

fix: Add Synapse Credential User role to app

---

src/core/20_appservice.tf

Add environment variables to app-api for SDI code feature.
Implementation of SDI code feature.
---

feat: [PFI-3] Add config for SDI code feature

---

src/core/20_storage.tf

- Add private endpoint to the "public" storage account.
The app needs to reach the public storage internally from whithin the VNET.
---

fix: [PFI-4] Allow internal access to public storage

---

src/core/20_appservice.tf

- SELF_CARE_TIMEOUT -> true
Configure timeout to self-care
---

fix(core): Self care timeout

---

src/core/20_functionapp.tf

-------
Add environment variables to "send email" function app.
Configure function app to send emails to PSP.
---

feat: [PFI-8] Function app env for sending emails to PSP

---

.github/workflows/static_analysis.yml
src/core/99_main.tf.ci

No changes to infra, just fix the static analysis.
Azure DevOps folder analysis was disabled.
---

chore: Fix static analysis

---

src/core/20_functionapp.tf

-------
as in title
connect func to storage
---

feat: Add env for connecting func to storage

---

src/core/20_appservice.tf

* Add App Service environment variables for app reaching public storage REL folder.
Being able to interact with REL from App Service
---

feat: [PFI-23] Add app config for REL targeting in public storage

---

src/core/20_storage.tf
src/core/99_variables.tf
src/core/env/prod/terraform.tfvars

Add ACL to fat<env>dls storage account.
Allowing integration with pagoPA data lake.
---

feat: [PFI-29] ACL for pagoPA DL to dls storage

---

src/core/20_appservice.tf
src/core/20_functionapp_durable.tf
src/core/20_synapse.tf

* Env keys for notifications
* Fix env keys syntax (colon not allowed)
* Fix func url in synapse linked service
---

feat: Env keys for notifications

---

src/core/80_observability.tf
src/core/99_refactoring.tf

-------
* Diagnostic settings to send monitoring data to log analytics workspace for Function Apps
* Diagnostic settings for app services and app gateway in UAT (in PROD a policy already got it)
Monitoring.
---

feat: Diagnostic settings for app, func, agw

---

src/core/.terraform.lock.hcl

-------
* Upgrade Terraform providers to latest version matching constraints.
Enjoy new feature and fixes.
---

build: Upgrade terraform providers

---

src/core/20_appservice.tf

-------
As in title
EOL of node 18
---
Was set manually in prod, just reported in code

feat: Upgrade node to 22

---

src/core/20_functionapp.tf

-------
As in title
Config
---

feat: Config env variables for integration func

---

src/core/20_functionapp.tf

* Environment variables of integration function for connecting to REL storage account
---

feat: Integration func config for connecting to REL storage account

---

src/core/20_appservice.tf

As in title.
Reach the slot within the VNET, useful for health checks and tests.
---

fix: Private endpoint for staging app slot

---

src/core/init-db/prod/auth.sql
src/core/init-db/uat/auth.sql
src/core/init-db/view-auth.sql

Permisison to execute some stored procedures.
Use stored procedure in SQL Server.
Manual apply (SQL scripts are not under Terraform).
---

chore: Stored procedure permissions
